config/routes.rb
Rails.application.routes.draw do
  resources :gams_paths
  get 'gams_path/edit'

  get 'gams_path/update'

  resources :translinks
  resources :institutes
  resources :students

  root   'static_pages#home'
  get    '/about', to: 'static_pages#about'
  get    '/contact', to: 'contacts#new'
  get    '/signup', to: 'users#new'
  get    '/login', to: 'sessions#new'
  get    'matching_start', to: 'static_pages#matching_start'
  post   '/login', to: 'sessions#create'
  post   '/signup', to: 'users#new'
  delete '/logout', to: 'sessions#destroy'
  match '/contacts', to: 'contacts#new', via: 'get'
  resources :contacts, only: [:new, :create]
  resources :users
  get 'show_matching_and_ofv', to: 'translinks#show_matching_and_ofv'
  post 'translinks/delete_matching', :to => 'translinks#delete_matching'
  post 'translinks/optimize', :to => 'translinks#optimize'
  post 'translinks/show_matching_and_ofv', :to => 'translinks#show_matching_and_ofv'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The creators of this application are Emelie Dümpelmann and Rabea Schulze. They are both current masters students at the Leibniz University in Hanover.
  <br>
  For further information please contact us via
  <%= mail_to("matching18@gmail.com", "Email", :style=> "font-weight: bold")%> or use the <%= link_to "Contact form", contact_path, :style=> "font-weight: bold" %>.
</p>

<p><strong>Emelie Dümpelmann</strong></p>
<dl class="dl-horizontal">
  <dt>
      <div class="image">
        <%=image_tag("Emelie.jpg", height: 250, alt: "Emelie", src:"app/assets/images/Emelie.jpg") %>
      </div>
  </dt>
  <br>
  <br>
  <br>
  <dd> <strong> Name: </strong> Emelie Dümpelmann <br>
       <strong> Birthdate: </strong> 26.11.1993 in Helmstedt <br>
       <strong> 2004-2012: </strong> High-school diploma <br>
       <strong> 2012-2016: </strong> B.Sc. Business Economics <br>
       <strong> 2016-2018: </strong> M.Sc. Business Sciences <br>
  </dd>
</dl>
<br>
<br>
<p><strong>Rabea Schulze</strong></p>
<dl class="dl-horizontal">
  <dt>
    <div class="image">
      <%=image_tag("Rabea.jpg", height: 250, alt: "Rabea", src:"app/assets/images/Rabea.jpg") %>
    </div>
  </dt>
  <br>
  <br>
  <br>
  <dd> <strong> Name: </strong> Rabea Schulze <br>
       <strong> Birthdate: </strong> 20.09.1994 in Celle <br>
       <strong> 2004-2012: </strong> High-school diploma <br>
       <strong> 2012-2016: </strong> B.Sc. Economics <br>
       <strong> 2016-2019: </strong> M.Sc. Business Sciences <br>
  </dd>
</dl>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <h1>Welcome to the Matching App</h1>
  <h3><strong>Description:</strong></h3>
  <h3>
    This is the home page for a matching application. The intention is to allocate Bachelor
    students who are close to write their bachelor thesis to institutes of the underlying university.
    The application should provide an optimal solution so that the sorrow of the students is as small as possible.
  </h3>
  <%=image_tag("Matching.png", alt: "Matching", src:"app/assets/images/Matching.png") %>
  </div>
  <div class="button">
  <%= button_to "Sign up now!", signup_path, class: "btn btn-primary" %>
</div>

app/views/static_pages/matching_start.html.erb
<% provide(:title, 'Matching App') %>

<h1>The Matching App </h1>
<br>

  <div class="linkcontainer">
    <div class="centerwrapper">
        <div class="image-icon">
          <%= link_to image_tag("student.png", height: '100', alt: 'Student logo'), students_path, "data-turbolinks": "false"  %> <br>
          <%= link_to 'Go to student administration', students_path, "data-turbolinks": "false" %>
        </div>

        <div class="image-icon">
          <%= link_to image_tag("university.png", height: '100', alt: 'Institut logo'), institutes_path, "data-turbolinks": "false"  %> <br>
          <%= link_to 'Go to institute administration', institutes_path, "data-turbolinks": "false" %>
        </div>

        <div class="image">
          <%= link_to image_tag("Goal2.png", height: '100', alt: 'Goal logo'), :controller => 'translinks', :action => 'show_matching_and_ofv', "data-turbolinks": "false"  %> <br>
          <%= link_to 'View Matching and Objective Function Value', :controller => 'translinks', :action =>  'show_matching_and_ofv', "data-turbolinks": "false" %>
        </div>
    </div>
    <br>
    <br> <br>
    <br> <br>

      <div class = "button" >
        <%= button_to "Delete old Matching", {:controller => 'translinks', :action =>  'delete_matching'},
        {:class => "btn btn-primary"} %>
        <br>
        <%= button_to "Optimize", {:controller => 'translinks', :action =>  'optimize'},
        {:class => "btn btn-primary"} %>
        <br>
        <br>
      </div>
</div>
<br> <br>