config/routes.rb
Rails.application.routes.draw do
  resources :gams_paths
  get 'gams_path/edit'

  get 'gams_path/update'

  resources :translinks
  resources :institutes
  resources :students

  root   'static_pages#home'
  get    '/about', to: 'static_pages#about'
  get    '/contact', to: 'contacts#new'
  get    '/signup', to: 'users#new'
  get    '/login', to: 'sessions#new'
  get    'matching_start', to: 'static_pages#matching_start'
  post   '/login', to: 'sessions#create'
  post   '/signup', to: 'users#new'
  delete '/logout', to: 'sessions#destroy'
  match '/contacts', to: 'contacts#new', via: 'get'
  resources :contacts, only: [:new, :create]
  resources :users
  get 'show_matching_and_ofv', to: 'translinks#show_matching_and_ofv'
  post 'translinks/delete_matching', :to => 'translinks#delete_matching'
  post 'translinks/optimize', :to => 'translinks#optimize'
  post 'translinks/show_matching_and_ofv', :to => 'translinks#show_matching_and_ofv'
end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :institute
    has_many :translinks, :dependent => :destroy
    accepts_nested_attributes_for :translinks
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  load_and_authorize_resource
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    if can? :optimize, Translink
    @students = Student.all
    else
    @students = Student.where(students: {name: current_user.name})
    end

    respond_to do |format|
      format.html
      format.xls

    end
  end
  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

    # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def be
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :studentnumber, :institute, :preference_value, :institute_id)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   <%= form.label :name %>
   <%= form.text_field :name, id: :student_name %>
 </div>

  <div class="field">
    <%= form.label :studentnumber %>
    <%= form.number_field :studentnumber, id: :student_studentnumber %>
  </div>

  <div class="field">
    <%= form.label 'Choose Institute' %><br />
    <%= form.collection_select :institute_id, Institute.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :preference_value %>
    <%= form.number_field :preference_value, id: :student_preference_value %>
  </div>

  <div class="button">
    <%= form.submit "Create Student", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/students/edit.html.erb
<% provide(:title, "Editing Student") %>
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path, "data-turbolinks": "false"  %>

app/views/students/index.html.erb
<% provide(:title, "Students") %>

<h1>Students</h1>

<%= link_to 'Excel Download', students_path(:format => :xls) %>

<table id="students" class="display">
  <thead>
    <tr>
      <th>Name</th>
      <th>Studentnumber</th>
      <th>Institute</th>
      <th>Preference Value</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.studentnumber %></td>
        <td><%= student.institute.name %></td>
        <td><%= student.preference_value %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>
<br>
<%= link_to 'Back to Matching', matching_start_path %>

app/views/students/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Students">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Student</Data></Cell>
        <Cell><Data ss:Type="String">Studentnumber</Data></Cell>
        <Cell><Data ss:Type="String">Institute</Data></Cell>
        <Cell><Data ss:Type="String">Preference value</Data></Cell>
      </Row>
    <% @students.each do |student| %>
      <Row>
        <Cell><Data ss:Type="String"><%= student.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= student.studentnumber %></Data></Cell>
        <Cell><Data ss:Type="String"><%= student.institute.name %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= student.preference_value %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/students/new.html.erb
<% provide(:title, "New Student") %>
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path, "data-turbolinks": "false"  %>

app/views/students/show.html.erb
<% provide(:title, "Student") %>

<p>
  <strong>Name:</strong>
  <%= best_in_place @student, :name %>
</p>

<p>
  <b>Institute:</b>
  <%= @student.institute.name %>
</p>


<p>
  <strong>Studentnumber:</strong>
  <%= @student.studentnumber %>
</p>

<p>
  <strong>Preference value:</strong>
  <%= @student.preference_value %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path, "data-turbolinks": "false"  %>