config/routes.rb
Rails.application.routes.draw do
  resources :gams_paths
  get 'gams_path/edit'

  get 'gams_path/update'

  resources :translinks
  resources :institutes
  resources :students

  root   'static_pages#home'
  get    '/about', to: 'static_pages#about'
  get    '/contact', to: 'contacts#new'
  get    '/signup', to: 'users#new'
  get    '/login', to: 'sessions#new'
  get    'matching_start', to: 'static_pages#matching_start'
  post   '/login', to: 'sessions#create'
  post   '/signup', to: 'users#new'
  delete '/logout', to: 'sessions#destroy'
  match '/contacts', to: 'contacts#new', via: 'get'
  resources :contacts, only: [:new, :create]
  resources :users
  get 'show_matching_and_ofv', to: 'translinks#show_matching_and_ofv'
  post 'translinks/delete_matching', :to => 'translinks#delete_matching'
  post 'translinks/optimize', :to => 'translinks#optimize'
  post 'translinks/show_matching_and_ofv', :to => 'translinks#show_matching_and_ofv'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    @user = user || User.new # in case of a new user
    @user.roles.each { |role| send(role.name.downcase) }

    if @user.roles.size == 0
      can [:index, :new, :create], User
    end
  end

  def student
    can [:index, :edit, :show, :be, :update, :destroy], Student
    can [:index, :show, :edit, :destroy, :update], User
  end

  def institute
    can [:index, :edit, :show, :be, :update, :destroy], Institute
    can [:index, :show, :edit, :destroy, :update], User
  end

  def admin
    can :manage, :all
  end

  def guest
    can [:index, :new, :create, :edit, :update ], User
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message, :validate => true
  attribute :nickname, :captcha => true

  #Declare the email headers. It accepts anything the mail method in ActionMailer accepts.
  def headers
    {
      :subject => "Message from Matching App",
      :to => "schulzerabea@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/gams_path.rb
class GamsPath < ApplicationRecord
  validates :gams_path_url, presence: true
end

app/models/institute.rb
class Institute < ApplicationRecord
    has_many :students, dependent: :destroy
    has_many :translinks, :dependent => :destroy
    accepts_nested_attributes_for :translinks
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :assignments
  has_many :users, through: :assignments

  validates :name, presence: true, uniqueness: true

end

app/models/student.rb
class Student < ApplicationRecord
    belongs_to :institute
    has_many :translinks, :dependent => :destroy
    accepts_nested_attributes_for :translinks
end

app/models/translink.rb
class Translink < ApplicationRecord
  belongs_to :student
  belongs_to :institute
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :assignments
  has_many :roles, through: :assignments

  before_save { email.downcase! }
# example of a nested hash!
  validates(:name, {presence: true, length: { maximum: 50}})
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                  format: { with: VALID_EMAIL_REGEX },
                  uniqueness: {case_sensitive: false}

  has_secure_password
  validates(:password, {presence: true, length: { minimum: 6}, allow_nil: true})

  # Returns the hash digest of the given string.
   def User.digest(string)
     cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                   BCrypt::Engine.cost
     BCrypt::Password.create(string, cost: cost)
   end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:success] = 'Thank you for your message. We will contact you soon!'
      render :new
    else
      flash.now[:error] = 'Can not send message.'
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
    @roles = Role.where.not(id: 1)
  end

  def create
   @user = User.new(user_params)
    if @user.save
     log_in @user
     # Create Student
     if @user.role_ids.include?(2)
     @student = Student.new
     flash[:success] = "Welcome to the Matching App!"
     redirect_to @student
     # Create Institute
     elsif @user.role_ids.include?(3)
     @institute = Institute.new
     flash[:success] = "Welcome to the Matching App!"
     redirect_to @institute
     end
    else
     render :new
    end
  end

 def edit
   @user = User.find(params[:id])
   if can? :optimize, Translink
     @roles = Role.all
   else
     @roles = Role.where.not(id: 1)
   end
 end

 def update
   @user = User.find(params[:id])
   if @user.update_attributes(user_params)
     flash[:success] = "Profile updated"
     redirect_to @user
   else
     render 'edit'
   end
 end

 def destroy
  User.find(params[:id]).destroy
  flash[:success] = "User deleted"
  redirect_to users_url
 end

 private

   def user_params
     params.require(:user).permit(:name, :email, :password,
                                  :password_confirmation, :birthday, :study_programme,
                                  :semester, :head_of_institute, :research_fields, role_ids: [])
   end

   # Before filters

   # Confirms the correct user.
   def correct_user
     if can? :optimize, Translink
       @user = User.find(params[:id])
     else
       @user = User.find(params[:id])
       redirect_to(root_url) unless current_user?(@user)
     end
   end

   # Confirms an admin user.
   def admin_user
     redirect_to(root_url) unless current_user.admin?
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
  base_title = "Matching App"
  if page_title.empty?
    base_title
  else
    page_title + " | " + base_title
  end
end
end

app/helpers/gams_paths_helper.rb
module GamsPathsHelper
end

app/helpers/institutes_helper.rb
module InstitutesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
      @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/translinks_helper.rb
module TranslinksHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Matching App by Emelie Dümpelmann and Rabea Schulze
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <br>
    <dl class="dl-horizontal">
      <dt>
    <%= link_to image_tag("Puzzle.png", height: 40, alt: 'Puzzle Logo'), root_path, id: 'logo' %>
      </dt>
      <dd>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
            <li>
              <%= link_to "Users", users_path %>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Apps <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Matching", matching_start_path %></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", logout_path, method: :delete %>
                </li>
              </ul>
            </li>
            <% else %>
            <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </dd>
    </dl>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>